name: AI SDLC

on:
  workflow_call:
    inputs:
      stack:
        required: false
        type: string
        default: "unknown"
      test_command:
        required: false
        type: string
        default: "echo no tests"
      python_version:
        required: false
        type: string
        default: "3.11.0"
    secrets:
      TAILSCALE_AUTHKEY:
        required: true
      LITELLM_URL:
        required: true
      LITELLM_MASTER_KEY:
        required: true

jobs:
  ai-task:
    runs-on: ubuntu-latest
    steps:
      - run: echo stack is ${{ inputs.stack }}
